# Generated by Django 4.0.5 on 2022-08-09 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_post_class_group_post_dateofbirth_post_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='dateofbirth',
            new_name='dateshare',
        ),
    ]
