# Generated by Django 4.0.5 on 2022-08-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_post_name2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='class_group',
        ),
        migrations.RemoveField(
            model_name='post',
            name='email',
        ),
        migrations.AlterField(
            model_name='post',
            name='name2',
            field=models.CharField(max_length=100, null=True, verbose_name='Post name2'),
        ),
    ]
