# Generated by Django 4.0.5 on 2022-08-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0007_remove_post_class_group_remove_post_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Blog Resmi'),
        ),
    ]
