# Generated by Django 4.0.5 on 2022-08-09 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0010_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='categori',
            field=models.CharField(choices=[('software', 'yazılım'), ('product', 'urun'), ('game', 'oyun'), ('technology', 'teknoloji'), ('movie', 'film')], default='post', max_length=20),
        ),
    ]
