# Generated by Django 4.0.5 on 2022-08-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0011_post_categori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='categori',
            field=models.CharField(choices=[('post', 'post'), ('software', 'yazılım'), ('product', 'urun'), ('game', 'oyun'), ('technology', 'teknoloji'), ('movie', 'film')], default='post', max_length=20),
        ),
    ]
