# Generated by Django 4.0.5 on 2022-08-11 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0016_alter_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='created_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='approved_comment',
        ),
    ]
