# Generated by Django 4.0.5 on 2022-08-11 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0019_rename_date_comments_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts'},
        ),
    ]
