# Generated by Django 4.0.5 on 2022-08-11 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0027_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dateshare']},
        ),
    ]
