# Generated by Django 4.0.5 on 2022-08-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0029_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='current',
            name='post',
            field=models.ManyToManyField(to='myApp.post'),
        ),
    ]
