# Generated by Django 4.0.5 on 2022-08-12 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0030_alter_current_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='current',
            name='post',
        ),
        migrations.AddField(
            model_name='current',
            name='post',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.post', verbose_name='Güncel Postlar'),
        ),
    ]
