# Generated by Django 4.0.5 on 2022-08-12 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0032_rename_current_currentpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='currentpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.post', verbose_name='Güncel Postlar'),
        ),
    ]
