# Generated by Django 4.0.5 on 2022-08-12 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0033_alter_currentpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentpost',
            name='post',
        ),
        migrations.AddField(
            model_name='currentpost',
            name='post',
            field=models.ManyToManyField(to='myApp.post', verbose_name='Popüler Post'),
        ),
    ]
