# Generated by Django 4.0.5 on 2022-08-12 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0034_remove_currentpost_post_currentpost_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentpost',
            name='post',
        ),
        migrations.AddField(
            model_name='currentpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myApp.post', verbose_name='Popüler Post'),
        ),
    ]
